// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvbatA3zwjuRylNFeDM0WfOXWoA6NoJM',
    appId: '1:666734849057:web:2a9da71d62d909445e4760',
    messagingSenderId: '666734849057',
    projectId: 'attendance-4b08d',
    authDomain: 'attendance-4b08d.firebaseapp.com',
    storageBucket: 'attendance-4b08d.firebasestorage.app',
    measurementId: 'G-VGJ7H326J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOPr3OdUmozusQejdnJbwVRlyf_WR-1U',
    appId: '1:666734849057:android:a3dd5466cb2b01655e4760',
    messagingSenderId: '666734849057',
    projectId: 'attendance-4b08d',
    storageBucket: 'attendance-4b08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1EfQS-PQ0oYtgnd9QCs8tWs2wV7C-eY',
    appId: '1:666734849057:ios:f871e766bdca29d55e4760',
    messagingSenderId: '666734849057',
    projectId: 'attendance-4b08d',
    storageBucket: 'attendance-4b08d.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1EfQS-PQ0oYtgnd9QCs8tWs2wV7C-eY',
    appId: '1:666734849057:ios:f871e766bdca29d55e4760',
    messagingSenderId: '666734849057',
    projectId: 'attendance-4b08d',
    storageBucket: 'attendance-4b08d.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrvbatA3zwjuRylNFeDM0WfOXWoA6NoJM',
    appId: '1:666734849057:web:b079440851aa6ccb5e4760',
    messagingSenderId: '666734849057',
    projectId: 'attendance-4b08d',
    authDomain: 'attendance-4b08d.firebaseapp.com',
    storageBucket: 'attendance-4b08d.firebasestorage.app',
    measurementId: 'G-Z0T81SZSVT',
  );
}
