/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eryl
 */
public class Pos_admin extends javax.swing.JFrame {

    /**
     * Creates new form Pos_admin
     */
    public Pos_admin() {
        initComponents();
      // jPanel1.setBackground(new Color(0,0,0,100));
      updatecombo();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtpcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtqty = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtpay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panel1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        panel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        Income = new javax.swing.JButton();
        Accounts = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "ProductName", "Quantity", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 740, 280));

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 332, 378));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 940, 120, 45));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 900, 110, 45));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 850, 110, 45));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Code:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, -1));

        txtpcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpcodeKeyPressed(evt);
            }
        });
        getContentPane().add(txtpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 38));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, -1));

        txtpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 70, -1));

        txtqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtqty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtqtyStateChanged(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 70, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 40, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 100, 38));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, -1));

        txtamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, 38));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 52));

        txtpay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 150, 81, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pay:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 130, -1, -1));

        txtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 70, 81, 41));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, -1, -1));

        txtbal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 230, 81, 41));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 52, 630, 370));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Balance:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        jButton2.setText("BILL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 95, 52));

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACCOUNT MANAGER.png"))); // NOI18N
        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 340, 480));

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACCOUNT MANAGER.png"))); // NOI18N
        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 180, 480));

        search.setForeground(new java.awt.Color(153, 153, 153));
        search.setText("Search Name");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, 160, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 160, 40));

        panel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACCOUNT MANAGER.png"))); // NOI18N
        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 1200, 480));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.png"))); // NOI18N
        jButton6.setText("Inventory");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Income.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Income.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-income-64.png"))); // NOI18N
        Income.setText("Income");
        Income.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeActionPerformed(evt);
            }
        });

        Accounts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-account-80.png"))); // NOI18N
        Accounts.setText("Accounts");
        Accounts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-40.png"))); // NOI18N
        jButton4.setText("LOGOUT");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Accounts, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Income, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 1000));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACCOUNT MANAGER.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 650, 480));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1240, 1010));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private static final DecimalFormat df = new DecimalFormat("0.00");
    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new LoginOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtpcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpcodeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String pcode = txtpcode.getText();
            
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
                pst = con.prepareStatement("SELECT * from product where id = ?");
                pst.setString(1, pcode);
                rs = pst.executeQuery();
                
                if(rs.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");
                }
                else
                {
                    String pname = rs.getString("prodname");
                    String price = rs.getString("price");
                    
                    txtpname.setText(pname.trim());
                    txtprice.setText(price.trim());
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtpcodeKeyPressed

    private void updatecombo(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
            pst = con.prepareStatement("SELECT distinct type from product");
            rs = pst.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("type"));
            }
        }catch (ClassNotFoundException ex){
            Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex){
             Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtqtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtqtyStateChanged
        // TODO add your handling code here:
        
        float qty = Float.parseFloat(txtqty.getValue().toString());
        float price = Float.parseFloat(txtprice.getText());
        float tot = qty * price;
        txtamount.setText(String.valueOf(df.format(tot)));
        
    }//GEN-LAST:event_txtqtyStateChanged

    public void Balance()
    {
        float total = Float.parseFloat(txtotal.getText());
        float pay = Float.parseFloat(txtpay.getText());
        float bal = pay - total;
        txtbal.setText(String.valueOf(df.format(bal)));
    }
    
    public void bill()
    {
        String total = txtotal.getText();
        String pay = txtpay.getText();
        String bal = txtbal.getText();
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable1.getModel();
        
        txtbill.setText(txtbill.getText() + "********************************************************************\n");
        txtbill.setText(txtbill.getText() + "                     BILL                                           \n");
        txtbill.setText(txtbill.getText() + "********************************************************************\n");
        
        //Heading
        txtbill.setText(txtbill.getText() + "Product" + "\t" + "Price" + "\t" + "Quantity" + "\t" + "Amount" + "\n");
        
        
        for(int i = 0; i < model.getRowCount(); i++)
        {
            String pname = (String)model.getValueAt(i, 1);
            String price = (String)model.getValueAt(i, 3);
            String amount = (String)model.getValueAt(i, 4);
            String quan = (String)model.getValueAt(i, 2);
            
            txtbill.setText(txtbill.getText() + pname + "\t" + price + "\t" + quan + "\t\t" + amount + "\n");
        }
        txtbill.setText(txtbill.getText() + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Subtotal: " + total + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Pay: " + pay + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Balance: " + bal + "\n");
        txtbill.setText(txtbill.getText() + "\n");
        txtbill.setText(txtbill.getText() + "********************************************************************\n");
        txtbill.setText(txtbill.getText() + "             THANK YOU COME AGAIN                           \n");
    
    
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String procode = txtpcode.getText();
            String quant = txtqty.getValue().toString();
            int quant1 = Integer.parseInt(quant);
            if(quant1>0)
            {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
                Statement st = con.createStatement();
                String query = "select * from product where id='" +procode+"'";
                rs = st.executeQuery(query);
                while(rs.next()){
                    String stockss = rs.getString(4);
                    int stocks = Integer.parseInt(stockss);
                    if(stocks>=quant1){
                        DefaultTableModel model = new DefaultTableModel();
                        model = (DefaultTableModel)jTable1.getModel();
                        model.addRow(new Object[]
                
                        {
                            txtpcode.getText(),
                            txtpname.getText(),
                            txtqty.getValue().toString(),
                            txtprice.getText(),
                            txtamount.getText(),
                        });
                        txtqty.setValue(0);
                        float sum = 0;
                        for(int i = 0; i<jTable1.getRowCount(); i ++ )
                        {
                            sum = sum + Float.parseFloat(jTable1.getValueAt(i, 4).toString());
        
                        }
                        txtotal.setText(String.valueOf(df.format(sum)));
                            txtpcode.setText("");
                            txtpname.setText("");
                            txtprice.setText("");
                            txtamount.setText("");
            
                        txtpcode.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(this, "Not enough stock: " + txtpname.getText());
                }
            }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Pos_staff.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "Quantity must be positive.");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtbill.setText("");
        boolean isnumeric = true;
        isnumeric = txtpay.getText().matches("-?\\d+(\\.\\d+)?");
        if(isnumeric)
        {
            float payposi = Float.parseFloat(txtpay.getText());
        if(payposi>0)
        {
        Balance();
        bill();
        }else{
            JOptionPane.showMessageDialog(null, "Pay must be positive.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Pay must not be empty.\nPay must not contain any character.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            
        

        if(jTable1.getSelectedRowCount()==1)
        {
            int column = 4;
            int row = jTable1.getSelectedRow();
            
            float sum = Float.parseFloat(txtotal.getText());
            sum = sum - Float.parseFloat(jTable1.getValueAt(row, column).toString());
            txtotal.setText(String.valueOf(df.format(sum)));
            tblModel.removeRow(jTable1.getSelectedRow());
            
            
            
        }else{
            if(jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Table is empty");
            }else{
                JOptionPane.showMessageDialog(this, "Please select row to delete");
            }
            
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Inventory_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!txtbal.getText().isEmpty())
        {
            float balance = Float.parseFloat(txtbal.getText());
            if(balance>=0){
        String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        String total = txtotal.getText();
        float moneyin = Float.parseFloat(total);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
            Statement st = con.createStatement();
            String query = "select * from earnings where Date='"+date+"'";
            String query2 = "update earnings set income=income+'"+moneyin+"'where Date='"+date+"'";
            String query3 = "INSERT into earnings"
                +"(Date, income)"
                +"VALUES (?,?)";
            rs = st.executeQuery(query);
                if(rs.next())
                {
                    pst = con.prepareStatement(query2);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Success");
                }else{
                    try {
                        con = DriverManager.getConnection("jdbc:mysql://localhost/salespos", "root", "");
                        pst = con.prepareStatement(query3);
                        pst.setString(1, date);
                        pst.setString(2, txtotal.getText());
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Success");
                        } catch (SQLException | HeadlessException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }
                    }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pos_staff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pos_staff.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        for(int i = 0; i < tblModel.getRowCount(); i++)
        {
            String procode = (String)tblModel.getValueAt(i, 0);
            String quan = (String)tblModel.getValueAt(i, 2);
            int quan1 = Integer.parseInt(quan);
            try
            {
                con = DriverManager.getConnection("jdbc:mysql://localhost/salespos", "root", "");
                String sql = "UPDATE product SET Stock=Stock-'"+quan1+"' WHERE id='"+procode+"'";
                pst = con.prepareStatement(sql);
                pst.executeUpdate();
                
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }

        }
        
        int rowstoremove = jTable1.getRowCount();
        for(int i = rowstoremove - 1; i>=0; i-- )
        { 
            tblModel.removeRow(i);
        }
        jTable2.setModel(new DefaultTableModel());
        txtqty.setValue(0);
        txtotal.setText("");
        txtpcode.setText("");
        txtpname.setText("");
        txtprice.setText("");
        txtamount.setText("");
        txtbill.setText("");
        txtpay.setText("");
        txtbal.setText("");
        search.setText("Search Name");
        search.setForeground(new Color(153,153,153));
        txtpcode.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Balance must no be negative.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Please finish billing first.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeActionPerformed
        // TODO add your handling code here:
        new Income_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IncomeActionPerformed

    private void AccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsActionPerformed
        // TODO add your handling code here:
        new Manage_accs().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccountsActionPerformed

    private void txtpnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER)
        {
            String pname = txtpname.getText();
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
                pst = con.prepareStatement("select * from product where prodname = ?");
                
                
                pst.setString(1, pname);
                rs = pst.executeQuery();
                
                
                if(rs.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");
                    
                }
                else
                {
                    String pcode = rs.getString("id");
                    String price = rs.getString("price");
                    txtpcode.setText(pcode.trim());
                    txtprice.setText(price.trim());
                
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Pos_staff.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Pos_staff.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_txtpnameKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTable2.setModel(new DefaultTableModel());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
            Statement st = con.createStatement();
            String query = "select * from product";
            rs = st.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i = 0; i<cols; i++)

            colName[i] = rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            

            String id, name, price, stock, expdate, type;
            while(rs.next())
            {
                id = rs.getString(1);
                name = rs.getString(2);
                price = rs.getString(3);
                stock = rs.getString(4);
                expdate = rs.getString(5);
                type = rs.getString(6);
                String[] row = {id, name, price, stock, expdate, type};
                model.addRow(row);
            }
            st.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login_staff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login_staff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectedRowIndex = jTable2.getSelectedRow();
        
        txtpcode.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtpname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtprice.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String select = jComboBox1.getSelectedItem().toString();
        jTable2.setModel(new DefaultTableModel());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
            pst = con.prepareStatement("SELECT * from product where type='"+select+"'");
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i = 0; i<cols; i++)

            colName[i] = rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            

            String id, name, price, stock, expdate, type;
            while(rs.next())
            {
                id = rs.getString(1);
                name = rs.getString(2);
                price = rs.getString(3);
                stock = rs.getString(4);
                expdate = rs.getString(5);
                type = rs.getString(6);
                String[] row = {id, name, price, stock, expdate, type};
                model.addRow(row);
            }
            pst.close();
            con.close();
        }catch (ClassNotFoundException ex){
            Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex){
             Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        if(search.getText().equals("Search Name")){
            search.setText("");
            search.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_searchFocusGained

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        jTable2.setModel(new DefaultTableModel());
        String searching = search.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/salespos","root","");
            String sql = "SELECT * from product where prodname like ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, "%" + searching + "%");
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i = 0; i<cols; i++)

            colName[i] = rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            

            String id, name, price, stock, expdate, type;
            while(rs.next())
            {
                id = rs.getString(1);
                name = rs.getString(2);
                price = rs.getString(3);
                stock = rs.getString(4);
                expdate = rs.getString(5);
                type = rs.getString(6);
                String[] row = {id, name, price, stock, expdate, type};
                model.addRow(row);
            }
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pos_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pos_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pos_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pos_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pos_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pos_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accounts;
    private javax.swing.JButton Income;
    private javax.swing.JLabel bg;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel panel1;
    private javax.swing.JLabel panel2;
    private javax.swing.JLabel panel3;
    private javax.swing.JTextField search;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtotal;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtpcode;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtqty;
    // End of variables declaration//GEN-END:variables
}
